### ISSUE TITLE
Make the code for the tutorial available

### ISSUE THREAD

**Issue by tom808** [PatrickLouys/no-framework-tutorial#45]
It would be nice if you could make the code for the tutorial available at each stage of the process.

Also, are you planning to continue this?

**Comment by PatrickLouys** [comment]
Yes I am planning to continue the tutorial, but I'm busy with job search at the moment.

There is a repo with the current state of the project that I'm using to write the tutorial. Snapshots of each chapter are not available and I am not sure how viable it would be to provide them since I've changed them a few times already, so maintaining those snapshots would be quite tedious.
